title: Yansiel Melendez
logo: /assets/img/headshot_circle.png
description: Cybersecurity Specialist with expertise in vulnerability management, threat mitigation, and regulatory compliance. My focus is on creating innovative solutions to protect critical assets and mitigate risks.
theme: jekyll-theme-minimal
